from .interHT import InterHTScorer
from .ComplEx import ComplEXScorer
from .DistMult import DistMultScorer
from .RotatE import RotatEScorer
from .RotateCT import RotateCTScorer
from .RotPro import RotProScorer
from .STransE import STransEScorer
from .TranS import TranSScorer
from .TransD import TransDScorer
from .TransE import TransEScorer
from .TripleRE import TripleREScorer
from .TranSparse import TranSparseScorer
